### ISSUE TITLE
use PipeTo.Overrid causes compile error

### ISSUE THREAD

**Issue by taiansu** [taiansu/pipe_to#2]
Compiling 1 file (.ex)

== Compilation error on file web/controllers/admin/user_controller.ex ==
*\* (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:864: Enum.find_index/2
    lib/pipe_to.ex:59: PipeTo.unpipe/2
    lib/pipe_to.ex:54: PipeTo.unpipe/2
    lib/pipe_to.ex:50: PipeTo.unpipe/1
    expanding macro: PipeTo.~>/2

**Comment by taiansu** [comment]
Fixed at  1ef362e.
